set nocompatible
filetype off
" Clear all rtp
set rtp=$VIMRUNTIME

" Add vader.vim to rtp
set rtp+=./vader.vim
set rtp+=./webapi-vim
set rtp+=../
filetype plugin indent on

let g:gql_servers = [
  \ {
  \   'host': 'https://api.github.com/graphql',
  \   'headers': {'Authorization': 'bearer $GITHUB_TOKEN'},
  \ },
  \]
